BEGIN TRY

	BEGIN TRANSACTION

	DECLARE 
        @C_CurrentUser varchar (128)
        , @C_CurrentDate datetime 
    SELECT 
        @C_CurrentUser = 'Mimosa IT - Manual'
        , @C_CurrentDate = getDate()

	        
    COMMIT TRANSACTION 
	PRINT 'EXECUTED SUCCESSFULLY'

END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION 
	PRINT	'ERROR_NUMBER ' + CONVERT(NVARCHAR(50),ERROR_NUMBER())
	PRINT	'ERROR_SEVERITY '+			CONVERT(NVARCHAR(50),ERROR_SEVERITY())
	PRINT	'ERROR_LINE	' +CONVERT(NVARCHAR(50),ERROR_LINE())
	PRINT	'ERROR_MESSAGE '+	ERROR_MESSAGE()
	PRINT 'EXECUTED UNSUCCESSFULLY'
END CATCH
GO

SELECT TOP 1 Version FROM dbo.TagVersion ORDER BY DateCreated DESC, Version DESC
GO