//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace Mimosa.Apartment.Silverlight.UI.ApartmentService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GlobalVariable", Namespace="http://schemas.datacontract.org/2004/07/Mimosa.Apartment.Web.UI")]
    public partial class GlobalVariable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Mimosa.Apartment.Silverlight.UI.ApartmentService.AppSettings AppSettingsField;
        
        private System.Nullable<System.DateTime> ApplicationCurrentDateTimeField;
        
        private Mimosa.Apartment.Silverlight.UI.ApartmentService.UserLogin UserLoginField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mimosa.Apartment.Silverlight.UI.ApartmentService.AppSettings AppSettings {
            get {
                return this.AppSettingsField;
            }
            set {
                if ((object.ReferenceEquals(this.AppSettingsField, value) != true)) {
                    this.AppSettingsField = value;
                    this.RaisePropertyChanged("AppSettings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ApplicationCurrentDateTime {
            get {
                return this.ApplicationCurrentDateTimeField;
            }
            set {
                if ((this.ApplicationCurrentDateTimeField.Equals(value) != true)) {
                    this.ApplicationCurrentDateTimeField = value;
                    this.RaisePropertyChanged("ApplicationCurrentDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mimosa.Apartment.Silverlight.UI.ApartmentService.UserLogin UserLogin {
            get {
                return this.UserLoginField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLoginField, value) != true)) {
                    this.UserLoginField = value;
                    this.RaisePropertyChanged("UserLogin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppSettings", Namespace="http://schemas.datacontract.org/2004/07/Mimosa.Apartment.Web.UI")]
    public partial class AppSettings : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ReportLocalizationField;
        
        private string ReportServerUrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportLocalization {
            get {
                return this.ReportLocalizationField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportLocalizationField, value) != true)) {
                    this.ReportLocalizationField = value;
                    this.RaisePropertyChanged("ReportLocalization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportServerUrl {
            get {
                return this.ReportServerUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportServerUrlField, value) != true)) {
                    this.ReportServerUrlField = value;
                    this.RaisePropertyChanged("ReportServerUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserLogin", Namespace="http://schemas.datacontract.org/2004/07/Mimosa.Apartment.Web.UI")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mimosa.Apartment.Silverlight.UI.ApartmentService.GlobalVariable))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mimosa.Apartment.Silverlight.UI.ApartmentService.AppSettings))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Mimosa.Apartment.Common.AspUser>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Mimosa.Apartment.Common.Country>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mimosa.Apartment.Common.Country))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mimosa.Apartment.Common.Record))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Mimosa.Apartment.Common.ContactInformation>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mimosa.Apartment.Common.ContactInformation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Mimosa.Apartment.Common.Customer>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mimosa.Apartment.Common.Customer))]
    public partial class UserLogin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Mimosa.Apartment.Common.AspUser AspUserField;
        
        private bool IsUserAdministratorField;
        
        private bool IsUserCustomerField;
        
        private System.Nullable<int> UserCustomerIdField;
        
        private string UserNameField;
        
        private string UserOrganisationWeekdayField;
        
        private System.Guid UserUserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mimosa.Apartment.Common.AspUser AspUser {
            get {
                return this.AspUserField;
            }
            set {
                if ((object.ReferenceEquals(this.AspUserField, value) != true)) {
                    this.AspUserField = value;
                    this.RaisePropertyChanged("AspUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUserAdministrator {
            get {
                return this.IsUserAdministratorField;
            }
            set {
                if ((this.IsUserAdministratorField.Equals(value) != true)) {
                    this.IsUserAdministratorField = value;
                    this.RaisePropertyChanged("IsUserAdministrator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUserCustomer {
            get {
                return this.IsUserCustomerField;
            }
            set {
                if ((this.IsUserCustomerField.Equals(value) != true)) {
                    this.IsUserCustomerField = value;
                    this.RaisePropertyChanged("IsUserCustomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserCustomerId {
            get {
                return this.UserCustomerIdField;
            }
            set {
                if ((this.UserCustomerIdField.Equals(value) != true)) {
                    this.UserCustomerIdField = value;
                    this.RaisePropertyChanged("UserCustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserOrganisationWeekday {
            get {
                return this.UserOrganisationWeekdayField;
            }
            set {
                if ((object.ReferenceEquals(this.UserOrganisationWeekdayField, value) != true)) {
                    this.UserOrganisationWeekdayField = value;
                    this.RaisePropertyChanged("UserOrganisationWeekday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserUserId {
            get {
                return this.UserUserIdField;
            }
            set {
                if ((this.UserUserIdField.Equals(value) != true)) {
                    this.UserUserIdField = value;
                    this.RaisePropertyChanged("UserUserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ApartmentService.ApartmentService")]
    public interface ApartmentService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ApartmentService/SelectSessionId", ReplyAction="urn:ApartmentService/SelectSessionIdResponse")]
        System.IAsyncResult BeginSelectSessionId(System.AsyncCallback callback, object asyncState);
        
        string EndSelectSessionId(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ApartmentService/GetGlobalVariable", ReplyAction="urn:ApartmentService/GetGlobalVariableResponse")]
        System.IAsyncResult BeginGetGlobalVariable(System.AsyncCallback callback, object asyncState);
        
        Mimosa.Apartment.Silverlight.UI.ApartmentService.GlobalVariable EndGetGlobalVariable(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ApartmentService/GetAppSettings", ReplyAction="urn:ApartmentService/GetAppSettingsResponse")]
        System.IAsyncResult BeginGetAppSettings(System.AsyncCallback callback, object asyncState);
        
        Mimosa.Apartment.Silverlight.UI.ApartmentService.AppSettings EndGetAppSettings(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ApartmentService/GetUserLogin", ReplyAction="urn:ApartmentService/GetUserLoginResponse")]
        System.IAsyncResult BeginGetUserLogin(System.AsyncCallback callback, object asyncState);
        
        Mimosa.Apartment.Silverlight.UI.ApartmentService.UserLogin EndGetUserLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ApartmentService/GetAspUser", ReplyAction="urn:ApartmentService/GetAspUserResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mimosa.Apartment.Silverlight.UI.ApartmentService.GlobalVariable))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mimosa.Apartment.Silverlight.UI.ApartmentService.AppSettings))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mimosa.Apartment.Silverlight.UI.ApartmentService.UserLogin))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Mimosa.Apartment.Common.AspUser>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Mimosa.Apartment.Common.Country>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mimosa.Apartment.Common.Country))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mimosa.Apartment.Common.Record))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Mimosa.Apartment.Common.ContactInformation>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mimosa.Apartment.Common.ContactInformation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Mimosa.Apartment.Common.Customer>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mimosa.Apartment.Common.Customer))]
        System.IAsyncResult BeginGetAspUser(System.Guid userId, System.AsyncCallback callback, object asyncState);
        
        Mimosa.Apartment.Common.AspUser EndGetAspUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ApartmentService/ListAspUser", ReplyAction="urn:ApartmentService/ListAspUserResponse")]
        System.IAsyncResult BeginListAspUser(System.Nullable<int> orgId, System.Nullable<System.Guid> userId, System.Nullable<bool> isLegacy, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<Mimosa.Apartment.Common.AspUser> EndListAspUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ApartmentService/UnlockAspUser", ReplyAction="urn:ApartmentService/UnlockAspUserResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mimosa.Apartment.Silverlight.UI.ApartmentService.GlobalVariable))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mimosa.Apartment.Silverlight.UI.ApartmentService.AppSettings))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mimosa.Apartment.Silverlight.UI.ApartmentService.UserLogin))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Mimosa.Apartment.Common.AspUser>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Mimosa.Apartment.Common.Country>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mimosa.Apartment.Common.Country))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mimosa.Apartment.Common.Record))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Mimosa.Apartment.Common.ContactInformation>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mimosa.Apartment.Common.ContactInformation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Mimosa.Apartment.Common.Customer>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mimosa.Apartment.Common.Customer))]
        System.IAsyncResult BeginUnlockAspUser(Mimosa.Apartment.Common.AspUser oldUser, System.AsyncCallback callback, object asyncState);
        
        Mimosa.Apartment.Common.AspUser EndUnlockAspUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ApartmentService/SaveAspUser", ReplyAction="urn:ApartmentService/SaveAspUserResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mimosa.Apartment.Silverlight.UI.ApartmentService.GlobalVariable))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mimosa.Apartment.Silverlight.UI.ApartmentService.AppSettings))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mimosa.Apartment.Silverlight.UI.ApartmentService.UserLogin))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Mimosa.Apartment.Common.AspUser>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Mimosa.Apartment.Common.Country>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mimosa.Apartment.Common.Country))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mimosa.Apartment.Common.Record))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Mimosa.Apartment.Common.ContactInformation>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mimosa.Apartment.Common.ContactInformation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Mimosa.Apartment.Common.Customer>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mimosa.Apartment.Common.Customer))]
        System.IAsyncResult BeginSaveAspUser(Mimosa.Apartment.Common.AspUser saveUser, System.AsyncCallback callback, object asyncState);
        
        Mimosa.Apartment.Common.AspUser EndSaveAspUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ApartmentService/ChangePassword", ReplyAction="urn:ApartmentService/ChangePasswordResponse")]
        System.IAsyncResult BeginChangePassword(string oldPassword, string newPassword, System.AsyncCallback callback, object asyncState);
        
        int EndChangePassword(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ApartmentService/ListCountry", ReplyAction="urn:ApartmentService/ListCountryResponse")]
        System.IAsyncResult BeginListCountry(System.Nullable<int> countryId, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<Mimosa.Apartment.Common.Country> EndListCountry(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ApartmentService/ListContactInformation", ReplyAction="urn:ApartmentService/ListContactInformationResponse")]
        System.IAsyncResult BeginListContactInformation(System.Nullable<int> contactInfoId, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<Mimosa.Apartment.Common.ContactInformation> EndListContactInformation(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ApartmentService/SaveContactInformation", ReplyAction="urn:ApartmentService/SaveContactInformationResponse")]
        System.IAsyncResult BeginSaveContactInformation(System.Collections.Generic.List<Mimosa.Apartment.Common.ContactInformation> saveList, System.AsyncCallback callback, object asyncState);
        
        void EndSaveContactInformation(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ApartmentService/ListCustomer", ReplyAction="urn:ApartmentService/ListCustomerResponse")]
        System.IAsyncResult BeginListCustomer(System.Nullable<int> customerId, string name, bool includeLegacy, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<Mimosa.Apartment.Common.Customer> EndListCustomer(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ApartmentService/SaveCustomer", ReplyAction="urn:ApartmentService/SaveCustomerResponse")]
        System.IAsyncResult BeginSaveCustomer(System.Collections.Generic.List<Mimosa.Apartment.Common.Customer> saveList, System.AsyncCallback callback, object asyncState);
        
        void EndSaveCustomer(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ApartmentServiceChannel : Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SelectSessionIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SelectSessionIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetGlobalVariableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetGlobalVariableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Mimosa.Apartment.Silverlight.UI.ApartmentService.GlobalVariable Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Mimosa.Apartment.Silverlight.UI.ApartmentService.GlobalVariable)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAppSettingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAppSettingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Mimosa.Apartment.Silverlight.UI.ApartmentService.AppSettings Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Mimosa.Apartment.Silverlight.UI.ApartmentService.AppSettings)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUserLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Mimosa.Apartment.Silverlight.UI.ApartmentService.UserLogin Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Mimosa.Apartment.Silverlight.UI.ApartmentService.UserLogin)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAspUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAspUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Mimosa.Apartment.Common.AspUser Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Mimosa.Apartment.Common.AspUser)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListAspUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListAspUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<Mimosa.Apartment.Common.AspUser> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<Mimosa.Apartment.Common.AspUser>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UnlockAspUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UnlockAspUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Mimosa.Apartment.Common.AspUser Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Mimosa.Apartment.Common.AspUser)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveAspUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveAspUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Mimosa.Apartment.Common.AspUser Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Mimosa.Apartment.Common.AspUser)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChangePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ChangePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListCountryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListCountryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<Mimosa.Apartment.Common.Country> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<Mimosa.Apartment.Common.Country>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListContactInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListContactInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<Mimosa.Apartment.Common.ContactInformation> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<Mimosa.Apartment.Common.ContactInformation>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<Mimosa.Apartment.Common.Customer> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<Mimosa.Apartment.Common.Customer>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApartmentServiceClient : System.ServiceModel.ClientBase<Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService>, Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService {
        
        private BeginOperationDelegate onBeginSelectSessionIdDelegate;
        
        private EndOperationDelegate onEndSelectSessionIdDelegate;
        
        private System.Threading.SendOrPostCallback onSelectSessionIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetGlobalVariableDelegate;
        
        private EndOperationDelegate onEndGetGlobalVariableDelegate;
        
        private System.Threading.SendOrPostCallback onGetGlobalVariableCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAppSettingsDelegate;
        
        private EndOperationDelegate onEndGetAppSettingsDelegate;
        
        private System.Threading.SendOrPostCallback onGetAppSettingsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUserLoginDelegate;
        
        private EndOperationDelegate onEndGetUserLoginDelegate;
        
        private System.Threading.SendOrPostCallback onGetUserLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAspUserDelegate;
        
        private EndOperationDelegate onEndGetAspUserDelegate;
        
        private System.Threading.SendOrPostCallback onGetAspUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginListAspUserDelegate;
        
        private EndOperationDelegate onEndListAspUserDelegate;
        
        private System.Threading.SendOrPostCallback onListAspUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginUnlockAspUserDelegate;
        
        private EndOperationDelegate onEndUnlockAspUserDelegate;
        
        private System.Threading.SendOrPostCallback onUnlockAspUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveAspUserDelegate;
        
        private EndOperationDelegate onEndSaveAspUserDelegate;
        
        private System.Threading.SendOrPostCallback onSaveAspUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginChangePasswordDelegate;
        
        private EndOperationDelegate onEndChangePasswordDelegate;
        
        private System.Threading.SendOrPostCallback onChangePasswordCompletedDelegate;
        
        private BeginOperationDelegate onBeginListCountryDelegate;
        
        private EndOperationDelegate onEndListCountryDelegate;
        
        private System.Threading.SendOrPostCallback onListCountryCompletedDelegate;
        
        private BeginOperationDelegate onBeginListContactInformationDelegate;
        
        private EndOperationDelegate onEndListContactInformationDelegate;
        
        private System.Threading.SendOrPostCallback onListContactInformationCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveContactInformationDelegate;
        
        private EndOperationDelegate onEndSaveContactInformationDelegate;
        
        private System.Threading.SendOrPostCallback onSaveContactInformationCompletedDelegate;
        
        private BeginOperationDelegate onBeginListCustomerDelegate;
        
        private EndOperationDelegate onEndListCustomerDelegate;
        
        private System.Threading.SendOrPostCallback onListCustomerCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveCustomerDelegate;
        
        private EndOperationDelegate onEndSaveCustomerDelegate;
        
        private System.Threading.SendOrPostCallback onSaveCustomerCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ApartmentServiceClient() {
        }
        
        public ApartmentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApartmentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApartmentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApartmentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<SelectSessionIdCompletedEventArgs> SelectSessionIdCompleted;
        
        public event System.EventHandler<GetGlobalVariableCompletedEventArgs> GetGlobalVariableCompleted;
        
        public event System.EventHandler<GetAppSettingsCompletedEventArgs> GetAppSettingsCompleted;
        
        public event System.EventHandler<GetUserLoginCompletedEventArgs> GetUserLoginCompleted;
        
        public event System.EventHandler<GetAspUserCompletedEventArgs> GetAspUserCompleted;
        
        public event System.EventHandler<ListAspUserCompletedEventArgs> ListAspUserCompleted;
        
        public event System.EventHandler<UnlockAspUserCompletedEventArgs> UnlockAspUserCompleted;
        
        public event System.EventHandler<SaveAspUserCompletedEventArgs> SaveAspUserCompleted;
        
        public event System.EventHandler<ChangePasswordCompletedEventArgs> ChangePasswordCompleted;
        
        public event System.EventHandler<ListCountryCompletedEventArgs> ListCountryCompleted;
        
        public event System.EventHandler<ListContactInformationCompletedEventArgs> ListContactInformationCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SaveContactInformationCompleted;
        
        public event System.EventHandler<ListCustomerCompletedEventArgs> ListCustomerCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SaveCustomerCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.BeginSelectSessionId(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSelectSessionId(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.EndSelectSessionId(System.IAsyncResult result) {
            return base.Channel.EndSelectSessionId(result);
        }
        
        private System.IAsyncResult OnBeginSelectSessionId(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).BeginSelectSessionId(callback, asyncState);
        }
        
        private object[] OnEndSelectSessionId(System.IAsyncResult result) {
            string retVal = ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).EndSelectSessionId(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSelectSessionIdCompleted(object state) {
            if ((this.SelectSessionIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SelectSessionIdCompleted(this, new SelectSessionIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SelectSessionIdAsync() {
            this.SelectSessionIdAsync(null);
        }
        
        public void SelectSessionIdAsync(object userState) {
            if ((this.onBeginSelectSessionIdDelegate == null)) {
                this.onBeginSelectSessionIdDelegate = new BeginOperationDelegate(this.OnBeginSelectSessionId);
            }
            if ((this.onEndSelectSessionIdDelegate == null)) {
                this.onEndSelectSessionIdDelegate = new EndOperationDelegate(this.OnEndSelectSessionId);
            }
            if ((this.onSelectSessionIdCompletedDelegate == null)) {
                this.onSelectSessionIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSelectSessionIdCompleted);
            }
            base.InvokeAsync(this.onBeginSelectSessionIdDelegate, null, this.onEndSelectSessionIdDelegate, this.onSelectSessionIdCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.BeginGetGlobalVariable(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetGlobalVariable(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mimosa.Apartment.Silverlight.UI.ApartmentService.GlobalVariable Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.EndGetGlobalVariable(System.IAsyncResult result) {
            return base.Channel.EndGetGlobalVariable(result);
        }
        
        private System.IAsyncResult OnBeginGetGlobalVariable(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).BeginGetGlobalVariable(callback, asyncState);
        }
        
        private object[] OnEndGetGlobalVariable(System.IAsyncResult result) {
            Mimosa.Apartment.Silverlight.UI.ApartmentService.GlobalVariable retVal = ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).EndGetGlobalVariable(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetGlobalVariableCompleted(object state) {
            if ((this.GetGlobalVariableCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetGlobalVariableCompleted(this, new GetGlobalVariableCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetGlobalVariableAsync() {
            this.GetGlobalVariableAsync(null);
        }
        
        public void GetGlobalVariableAsync(object userState) {
            if ((this.onBeginGetGlobalVariableDelegate == null)) {
                this.onBeginGetGlobalVariableDelegate = new BeginOperationDelegate(this.OnBeginGetGlobalVariable);
            }
            if ((this.onEndGetGlobalVariableDelegate == null)) {
                this.onEndGetGlobalVariableDelegate = new EndOperationDelegate(this.OnEndGetGlobalVariable);
            }
            if ((this.onGetGlobalVariableCompletedDelegate == null)) {
                this.onGetGlobalVariableCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetGlobalVariableCompleted);
            }
            base.InvokeAsync(this.onBeginGetGlobalVariableDelegate, null, this.onEndGetGlobalVariableDelegate, this.onGetGlobalVariableCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.BeginGetAppSettings(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAppSettings(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mimosa.Apartment.Silverlight.UI.ApartmentService.AppSettings Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.EndGetAppSettings(System.IAsyncResult result) {
            return base.Channel.EndGetAppSettings(result);
        }
        
        private System.IAsyncResult OnBeginGetAppSettings(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).BeginGetAppSettings(callback, asyncState);
        }
        
        private object[] OnEndGetAppSettings(System.IAsyncResult result) {
            Mimosa.Apartment.Silverlight.UI.ApartmentService.AppSettings retVal = ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).EndGetAppSettings(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAppSettingsCompleted(object state) {
            if ((this.GetAppSettingsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAppSettingsCompleted(this, new GetAppSettingsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAppSettingsAsync() {
            this.GetAppSettingsAsync(null);
        }
        
        public void GetAppSettingsAsync(object userState) {
            if ((this.onBeginGetAppSettingsDelegate == null)) {
                this.onBeginGetAppSettingsDelegate = new BeginOperationDelegate(this.OnBeginGetAppSettings);
            }
            if ((this.onEndGetAppSettingsDelegate == null)) {
                this.onEndGetAppSettingsDelegate = new EndOperationDelegate(this.OnEndGetAppSettings);
            }
            if ((this.onGetAppSettingsCompletedDelegate == null)) {
                this.onGetAppSettingsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAppSettingsCompleted);
            }
            base.InvokeAsync(this.onBeginGetAppSettingsDelegate, null, this.onEndGetAppSettingsDelegate, this.onGetAppSettingsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.BeginGetUserLogin(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUserLogin(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mimosa.Apartment.Silverlight.UI.ApartmentService.UserLogin Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.EndGetUserLogin(System.IAsyncResult result) {
            return base.Channel.EndGetUserLogin(result);
        }
        
        private System.IAsyncResult OnBeginGetUserLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).BeginGetUserLogin(callback, asyncState);
        }
        
        private object[] OnEndGetUserLogin(System.IAsyncResult result) {
            Mimosa.Apartment.Silverlight.UI.ApartmentService.UserLogin retVal = ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).EndGetUserLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUserLoginCompleted(object state) {
            if ((this.GetUserLoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUserLoginCompleted(this, new GetUserLoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUserLoginAsync() {
            this.GetUserLoginAsync(null);
        }
        
        public void GetUserLoginAsync(object userState) {
            if ((this.onBeginGetUserLoginDelegate == null)) {
                this.onBeginGetUserLoginDelegate = new BeginOperationDelegate(this.OnBeginGetUserLogin);
            }
            if ((this.onEndGetUserLoginDelegate == null)) {
                this.onEndGetUserLoginDelegate = new EndOperationDelegate(this.OnEndGetUserLogin);
            }
            if ((this.onGetUserLoginCompletedDelegate == null)) {
                this.onGetUserLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserLoginCompleted);
            }
            base.InvokeAsync(this.onBeginGetUserLoginDelegate, null, this.onEndGetUserLoginDelegate, this.onGetUserLoginCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.BeginGetAspUser(System.Guid userId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAspUser(userId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mimosa.Apartment.Common.AspUser Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.EndGetAspUser(System.IAsyncResult result) {
            return base.Channel.EndGetAspUser(result);
        }
        
        private System.IAsyncResult OnBeginGetAspUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid userId = ((System.Guid)(inValues[0]));
            return ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).BeginGetAspUser(userId, callback, asyncState);
        }
        
        private object[] OnEndGetAspUser(System.IAsyncResult result) {
            Mimosa.Apartment.Common.AspUser retVal = ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).EndGetAspUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAspUserCompleted(object state) {
            if ((this.GetAspUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAspUserCompleted(this, new GetAspUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAspUserAsync(System.Guid userId) {
            this.GetAspUserAsync(userId, null);
        }
        
        public void GetAspUserAsync(System.Guid userId, object userState) {
            if ((this.onBeginGetAspUserDelegate == null)) {
                this.onBeginGetAspUserDelegate = new BeginOperationDelegate(this.OnBeginGetAspUser);
            }
            if ((this.onEndGetAspUserDelegate == null)) {
                this.onEndGetAspUserDelegate = new EndOperationDelegate(this.OnEndGetAspUser);
            }
            if ((this.onGetAspUserCompletedDelegate == null)) {
                this.onGetAspUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAspUserCompleted);
            }
            base.InvokeAsync(this.onBeginGetAspUserDelegate, new object[] {
                        userId}, this.onEndGetAspUserDelegate, this.onGetAspUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.BeginListAspUser(System.Nullable<int> orgId, System.Nullable<System.Guid> userId, System.Nullable<bool> isLegacy, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListAspUser(orgId, userId, isLegacy, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<Mimosa.Apartment.Common.AspUser> Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.EndListAspUser(System.IAsyncResult result) {
            return base.Channel.EndListAspUser(result);
        }
        
        private System.IAsyncResult OnBeginListAspUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Nullable<int> orgId = ((System.Nullable<int>)(inValues[0]));
            System.Nullable<System.Guid> userId = ((System.Nullable<System.Guid>)(inValues[1]));
            System.Nullable<bool> isLegacy = ((System.Nullable<bool>)(inValues[2]));
            return ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).BeginListAspUser(orgId, userId, isLegacy, callback, asyncState);
        }
        
        private object[] OnEndListAspUser(System.IAsyncResult result) {
            System.Collections.Generic.List<Mimosa.Apartment.Common.AspUser> retVal = ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).EndListAspUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListAspUserCompleted(object state) {
            if ((this.ListAspUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListAspUserCompleted(this, new ListAspUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListAspUserAsync(System.Nullable<int> orgId, System.Nullable<System.Guid> userId, System.Nullable<bool> isLegacy) {
            this.ListAspUserAsync(orgId, userId, isLegacy, null);
        }
        
        public void ListAspUserAsync(System.Nullable<int> orgId, System.Nullable<System.Guid> userId, System.Nullable<bool> isLegacy, object userState) {
            if ((this.onBeginListAspUserDelegate == null)) {
                this.onBeginListAspUserDelegate = new BeginOperationDelegate(this.OnBeginListAspUser);
            }
            if ((this.onEndListAspUserDelegate == null)) {
                this.onEndListAspUserDelegate = new EndOperationDelegate(this.OnEndListAspUser);
            }
            if ((this.onListAspUserCompletedDelegate == null)) {
                this.onListAspUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListAspUserCompleted);
            }
            base.InvokeAsync(this.onBeginListAspUserDelegate, new object[] {
                        orgId,
                        userId,
                        isLegacy}, this.onEndListAspUserDelegate, this.onListAspUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.BeginUnlockAspUser(Mimosa.Apartment.Common.AspUser oldUser, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUnlockAspUser(oldUser, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mimosa.Apartment.Common.AspUser Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.EndUnlockAspUser(System.IAsyncResult result) {
            return base.Channel.EndUnlockAspUser(result);
        }
        
        private System.IAsyncResult OnBeginUnlockAspUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Mimosa.Apartment.Common.AspUser oldUser = ((Mimosa.Apartment.Common.AspUser)(inValues[0]));
            return ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).BeginUnlockAspUser(oldUser, callback, asyncState);
        }
        
        private object[] OnEndUnlockAspUser(System.IAsyncResult result) {
            Mimosa.Apartment.Common.AspUser retVal = ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).EndUnlockAspUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUnlockAspUserCompleted(object state) {
            if ((this.UnlockAspUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UnlockAspUserCompleted(this, new UnlockAspUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UnlockAspUserAsync(Mimosa.Apartment.Common.AspUser oldUser) {
            this.UnlockAspUserAsync(oldUser, null);
        }
        
        public void UnlockAspUserAsync(Mimosa.Apartment.Common.AspUser oldUser, object userState) {
            if ((this.onBeginUnlockAspUserDelegate == null)) {
                this.onBeginUnlockAspUserDelegate = new BeginOperationDelegate(this.OnBeginUnlockAspUser);
            }
            if ((this.onEndUnlockAspUserDelegate == null)) {
                this.onEndUnlockAspUserDelegate = new EndOperationDelegate(this.OnEndUnlockAspUser);
            }
            if ((this.onUnlockAspUserCompletedDelegate == null)) {
                this.onUnlockAspUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUnlockAspUserCompleted);
            }
            base.InvokeAsync(this.onBeginUnlockAspUserDelegate, new object[] {
                        oldUser}, this.onEndUnlockAspUserDelegate, this.onUnlockAspUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.BeginSaveAspUser(Mimosa.Apartment.Common.AspUser saveUser, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveAspUser(saveUser, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mimosa.Apartment.Common.AspUser Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.EndSaveAspUser(System.IAsyncResult result) {
            return base.Channel.EndSaveAspUser(result);
        }
        
        private System.IAsyncResult OnBeginSaveAspUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Mimosa.Apartment.Common.AspUser saveUser = ((Mimosa.Apartment.Common.AspUser)(inValues[0]));
            return ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).BeginSaveAspUser(saveUser, callback, asyncState);
        }
        
        private object[] OnEndSaveAspUser(System.IAsyncResult result) {
            Mimosa.Apartment.Common.AspUser retVal = ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).EndSaveAspUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveAspUserCompleted(object state) {
            if ((this.SaveAspUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveAspUserCompleted(this, new SaveAspUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveAspUserAsync(Mimosa.Apartment.Common.AspUser saveUser) {
            this.SaveAspUserAsync(saveUser, null);
        }
        
        public void SaveAspUserAsync(Mimosa.Apartment.Common.AspUser saveUser, object userState) {
            if ((this.onBeginSaveAspUserDelegate == null)) {
                this.onBeginSaveAspUserDelegate = new BeginOperationDelegate(this.OnBeginSaveAspUser);
            }
            if ((this.onEndSaveAspUserDelegate == null)) {
                this.onEndSaveAspUserDelegate = new EndOperationDelegate(this.OnEndSaveAspUser);
            }
            if ((this.onSaveAspUserCompletedDelegate == null)) {
                this.onSaveAspUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveAspUserCompleted);
            }
            base.InvokeAsync(this.onBeginSaveAspUserDelegate, new object[] {
                        saveUser}, this.onEndSaveAspUserDelegate, this.onSaveAspUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.BeginChangePassword(string oldPassword, string newPassword, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginChangePassword(oldPassword, newPassword, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.EndChangePassword(System.IAsyncResult result) {
            return base.Channel.EndChangePassword(result);
        }
        
        private System.IAsyncResult OnBeginChangePassword(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string oldPassword = ((string)(inValues[0]));
            string newPassword = ((string)(inValues[1]));
            return ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).BeginChangePassword(oldPassword, newPassword, callback, asyncState);
        }
        
        private object[] OnEndChangePassword(System.IAsyncResult result) {
            int retVal = ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).EndChangePassword(result);
            return new object[] {
                    retVal};
        }
        
        private void OnChangePasswordCompleted(object state) {
            if ((this.ChangePasswordCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ChangePasswordCompleted(this, new ChangePasswordCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ChangePasswordAsync(string oldPassword, string newPassword) {
            this.ChangePasswordAsync(oldPassword, newPassword, null);
        }
        
        public void ChangePasswordAsync(string oldPassword, string newPassword, object userState) {
            if ((this.onBeginChangePasswordDelegate == null)) {
                this.onBeginChangePasswordDelegate = new BeginOperationDelegate(this.OnBeginChangePassword);
            }
            if ((this.onEndChangePasswordDelegate == null)) {
                this.onEndChangePasswordDelegate = new EndOperationDelegate(this.OnEndChangePassword);
            }
            if ((this.onChangePasswordCompletedDelegate == null)) {
                this.onChangePasswordCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnChangePasswordCompleted);
            }
            base.InvokeAsync(this.onBeginChangePasswordDelegate, new object[] {
                        oldPassword,
                        newPassword}, this.onEndChangePasswordDelegate, this.onChangePasswordCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.BeginListCountry(System.Nullable<int> countryId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListCountry(countryId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<Mimosa.Apartment.Common.Country> Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.EndListCountry(System.IAsyncResult result) {
            return base.Channel.EndListCountry(result);
        }
        
        private System.IAsyncResult OnBeginListCountry(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Nullable<int> countryId = ((System.Nullable<int>)(inValues[0]));
            return ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).BeginListCountry(countryId, callback, asyncState);
        }
        
        private object[] OnEndListCountry(System.IAsyncResult result) {
            System.Collections.Generic.List<Mimosa.Apartment.Common.Country> retVal = ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).EndListCountry(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListCountryCompleted(object state) {
            if ((this.ListCountryCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListCountryCompleted(this, new ListCountryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListCountryAsync(System.Nullable<int> countryId) {
            this.ListCountryAsync(countryId, null);
        }
        
        public void ListCountryAsync(System.Nullable<int> countryId, object userState) {
            if ((this.onBeginListCountryDelegate == null)) {
                this.onBeginListCountryDelegate = new BeginOperationDelegate(this.OnBeginListCountry);
            }
            if ((this.onEndListCountryDelegate == null)) {
                this.onEndListCountryDelegate = new EndOperationDelegate(this.OnEndListCountry);
            }
            if ((this.onListCountryCompletedDelegate == null)) {
                this.onListCountryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListCountryCompleted);
            }
            base.InvokeAsync(this.onBeginListCountryDelegate, new object[] {
                        countryId}, this.onEndListCountryDelegate, this.onListCountryCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.BeginListContactInformation(System.Nullable<int> contactInfoId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListContactInformation(contactInfoId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<Mimosa.Apartment.Common.ContactInformation> Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.EndListContactInformation(System.IAsyncResult result) {
            return base.Channel.EndListContactInformation(result);
        }
        
        private System.IAsyncResult OnBeginListContactInformation(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Nullable<int> contactInfoId = ((System.Nullable<int>)(inValues[0]));
            return ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).BeginListContactInformation(contactInfoId, callback, asyncState);
        }
        
        private object[] OnEndListContactInformation(System.IAsyncResult result) {
            System.Collections.Generic.List<Mimosa.Apartment.Common.ContactInformation> retVal = ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).EndListContactInformation(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListContactInformationCompleted(object state) {
            if ((this.ListContactInformationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListContactInformationCompleted(this, new ListContactInformationCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListContactInformationAsync(System.Nullable<int> contactInfoId) {
            this.ListContactInformationAsync(contactInfoId, null);
        }
        
        public void ListContactInformationAsync(System.Nullable<int> contactInfoId, object userState) {
            if ((this.onBeginListContactInformationDelegate == null)) {
                this.onBeginListContactInformationDelegate = new BeginOperationDelegate(this.OnBeginListContactInformation);
            }
            if ((this.onEndListContactInformationDelegate == null)) {
                this.onEndListContactInformationDelegate = new EndOperationDelegate(this.OnEndListContactInformation);
            }
            if ((this.onListContactInformationCompletedDelegate == null)) {
                this.onListContactInformationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListContactInformationCompleted);
            }
            base.InvokeAsync(this.onBeginListContactInformationDelegate, new object[] {
                        contactInfoId}, this.onEndListContactInformationDelegate, this.onListContactInformationCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.BeginSaveContactInformation(System.Collections.Generic.List<Mimosa.Apartment.Common.ContactInformation> saveList, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveContactInformation(saveList, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.EndSaveContactInformation(System.IAsyncResult result) {
            base.Channel.EndSaveContactInformation(result);
        }
        
        private System.IAsyncResult OnBeginSaveContactInformation(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Collections.Generic.List<Mimosa.Apartment.Common.ContactInformation> saveList = ((System.Collections.Generic.List<Mimosa.Apartment.Common.ContactInformation>)(inValues[0]));
            return ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).BeginSaveContactInformation(saveList, callback, asyncState);
        }
        
        private object[] OnEndSaveContactInformation(System.IAsyncResult result) {
            ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).EndSaveContactInformation(result);
            return null;
        }
        
        private void OnSaveContactInformationCompleted(object state) {
            if ((this.SaveContactInformationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveContactInformationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveContactInformationAsync(System.Collections.Generic.List<Mimosa.Apartment.Common.ContactInformation> saveList) {
            this.SaveContactInformationAsync(saveList, null);
        }
        
        public void SaveContactInformationAsync(System.Collections.Generic.List<Mimosa.Apartment.Common.ContactInformation> saveList, object userState) {
            if ((this.onBeginSaveContactInformationDelegate == null)) {
                this.onBeginSaveContactInformationDelegate = new BeginOperationDelegate(this.OnBeginSaveContactInformation);
            }
            if ((this.onEndSaveContactInformationDelegate == null)) {
                this.onEndSaveContactInformationDelegate = new EndOperationDelegate(this.OnEndSaveContactInformation);
            }
            if ((this.onSaveContactInformationCompletedDelegate == null)) {
                this.onSaveContactInformationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveContactInformationCompleted);
            }
            base.InvokeAsync(this.onBeginSaveContactInformationDelegate, new object[] {
                        saveList}, this.onEndSaveContactInformationDelegate, this.onSaveContactInformationCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.BeginListCustomer(System.Nullable<int> customerId, string name, bool includeLegacy, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListCustomer(customerId, name, includeLegacy, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<Mimosa.Apartment.Common.Customer> Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.EndListCustomer(System.IAsyncResult result) {
            return base.Channel.EndListCustomer(result);
        }
        
        private System.IAsyncResult OnBeginListCustomer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Nullable<int> customerId = ((System.Nullable<int>)(inValues[0]));
            string name = ((string)(inValues[1]));
            bool includeLegacy = ((bool)(inValues[2]));
            return ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).BeginListCustomer(customerId, name, includeLegacy, callback, asyncState);
        }
        
        private object[] OnEndListCustomer(System.IAsyncResult result) {
            System.Collections.Generic.List<Mimosa.Apartment.Common.Customer> retVal = ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).EndListCustomer(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListCustomerCompleted(object state) {
            if ((this.ListCustomerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListCustomerCompleted(this, new ListCustomerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListCustomerAsync(System.Nullable<int> customerId, string name, bool includeLegacy) {
            this.ListCustomerAsync(customerId, name, includeLegacy, null);
        }
        
        public void ListCustomerAsync(System.Nullable<int> customerId, string name, bool includeLegacy, object userState) {
            if ((this.onBeginListCustomerDelegate == null)) {
                this.onBeginListCustomerDelegate = new BeginOperationDelegate(this.OnBeginListCustomer);
            }
            if ((this.onEndListCustomerDelegate == null)) {
                this.onEndListCustomerDelegate = new EndOperationDelegate(this.OnEndListCustomer);
            }
            if ((this.onListCustomerCompletedDelegate == null)) {
                this.onListCustomerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListCustomerCompleted);
            }
            base.InvokeAsync(this.onBeginListCustomerDelegate, new object[] {
                        customerId,
                        name,
                        includeLegacy}, this.onEndListCustomerDelegate, this.onListCustomerCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.BeginSaveCustomer(System.Collections.Generic.List<Mimosa.Apartment.Common.Customer> saveList, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveCustomer(saveList, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService.EndSaveCustomer(System.IAsyncResult result) {
            base.Channel.EndSaveCustomer(result);
        }
        
        private System.IAsyncResult OnBeginSaveCustomer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Collections.Generic.List<Mimosa.Apartment.Common.Customer> saveList = ((System.Collections.Generic.List<Mimosa.Apartment.Common.Customer>)(inValues[0]));
            return ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).BeginSaveCustomer(saveList, callback, asyncState);
        }
        
        private object[] OnEndSaveCustomer(System.IAsyncResult result) {
            ((Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService)(this)).EndSaveCustomer(result);
            return null;
        }
        
        private void OnSaveCustomerCompleted(object state) {
            if ((this.SaveCustomerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveCustomerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveCustomerAsync(System.Collections.Generic.List<Mimosa.Apartment.Common.Customer> saveList) {
            this.SaveCustomerAsync(saveList, null);
        }
        
        public void SaveCustomerAsync(System.Collections.Generic.List<Mimosa.Apartment.Common.Customer> saveList, object userState) {
            if ((this.onBeginSaveCustomerDelegate == null)) {
                this.onBeginSaveCustomerDelegate = new BeginOperationDelegate(this.OnBeginSaveCustomer);
            }
            if ((this.onEndSaveCustomerDelegate == null)) {
                this.onEndSaveCustomerDelegate = new EndOperationDelegate(this.OnEndSaveCustomer);
            }
            if ((this.onSaveCustomerCompletedDelegate == null)) {
                this.onSaveCustomerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveCustomerCompleted);
            }
            base.InvokeAsync(this.onBeginSaveCustomerDelegate, new object[] {
                        saveList}, this.onEndSaveCustomerDelegate, this.onSaveCustomerCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService CreateChannel() {
            return new ApartmentServiceClientChannel(this);
        }
        
        private class ApartmentServiceClientChannel : ChannelBase<Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService>, Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService {
            
            public ApartmentServiceClientChannel(System.ServiceModel.ClientBase<Mimosa.Apartment.Silverlight.UI.ApartmentService.ApartmentService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginSelectSessionId(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("SelectSessionId", _args, callback, asyncState);
                return _result;
            }
            
            public string EndSelectSessionId(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("SelectSessionId", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetGlobalVariable(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetGlobalVariable", _args, callback, asyncState);
                return _result;
            }
            
            public Mimosa.Apartment.Silverlight.UI.ApartmentService.GlobalVariable EndGetGlobalVariable(System.IAsyncResult result) {
                object[] _args = new object[0];
                Mimosa.Apartment.Silverlight.UI.ApartmentService.GlobalVariable _result = ((Mimosa.Apartment.Silverlight.UI.ApartmentService.GlobalVariable)(base.EndInvoke("GetGlobalVariable", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAppSettings(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAppSettings", _args, callback, asyncState);
                return _result;
            }
            
            public Mimosa.Apartment.Silverlight.UI.ApartmentService.AppSettings EndGetAppSettings(System.IAsyncResult result) {
                object[] _args = new object[0];
                Mimosa.Apartment.Silverlight.UI.ApartmentService.AppSettings _result = ((Mimosa.Apartment.Silverlight.UI.ApartmentService.AppSettings)(base.EndInvoke("GetAppSettings", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetUserLogin(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetUserLogin", _args, callback, asyncState);
                return _result;
            }
            
            public Mimosa.Apartment.Silverlight.UI.ApartmentService.UserLogin EndGetUserLogin(System.IAsyncResult result) {
                object[] _args = new object[0];
                Mimosa.Apartment.Silverlight.UI.ApartmentService.UserLogin _result = ((Mimosa.Apartment.Silverlight.UI.ApartmentService.UserLogin)(base.EndInvoke("GetUserLogin", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAspUser(System.Guid userId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = userId;
                System.IAsyncResult _result = base.BeginInvoke("GetAspUser", _args, callback, asyncState);
                return _result;
            }
            
            public Mimosa.Apartment.Common.AspUser EndGetAspUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                Mimosa.Apartment.Common.AspUser _result = ((Mimosa.Apartment.Common.AspUser)(base.EndInvoke("GetAspUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginListAspUser(System.Nullable<int> orgId, System.Nullable<System.Guid> userId, System.Nullable<bool> isLegacy, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = orgId;
                _args[1] = userId;
                _args[2] = isLegacy;
                System.IAsyncResult _result = base.BeginInvoke("ListAspUser", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<Mimosa.Apartment.Common.AspUser> EndListAspUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<Mimosa.Apartment.Common.AspUser> _result = ((System.Collections.Generic.List<Mimosa.Apartment.Common.AspUser>)(base.EndInvoke("ListAspUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUnlockAspUser(Mimosa.Apartment.Common.AspUser oldUser, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = oldUser;
                System.IAsyncResult _result = base.BeginInvoke("UnlockAspUser", _args, callback, asyncState);
                return _result;
            }
            
            public Mimosa.Apartment.Common.AspUser EndUnlockAspUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                Mimosa.Apartment.Common.AspUser _result = ((Mimosa.Apartment.Common.AspUser)(base.EndInvoke("UnlockAspUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSaveAspUser(Mimosa.Apartment.Common.AspUser saveUser, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = saveUser;
                System.IAsyncResult _result = base.BeginInvoke("SaveAspUser", _args, callback, asyncState);
                return _result;
            }
            
            public Mimosa.Apartment.Common.AspUser EndSaveAspUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                Mimosa.Apartment.Common.AspUser _result = ((Mimosa.Apartment.Common.AspUser)(base.EndInvoke("SaveAspUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginChangePassword(string oldPassword, string newPassword, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = oldPassword;
                _args[1] = newPassword;
                System.IAsyncResult _result = base.BeginInvoke("ChangePassword", _args, callback, asyncState);
                return _result;
            }
            
            public int EndChangePassword(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("ChangePassword", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginListCountry(System.Nullable<int> countryId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = countryId;
                System.IAsyncResult _result = base.BeginInvoke("ListCountry", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<Mimosa.Apartment.Common.Country> EndListCountry(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<Mimosa.Apartment.Common.Country> _result = ((System.Collections.Generic.List<Mimosa.Apartment.Common.Country>)(base.EndInvoke("ListCountry", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginListContactInformation(System.Nullable<int> contactInfoId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = contactInfoId;
                System.IAsyncResult _result = base.BeginInvoke("ListContactInformation", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<Mimosa.Apartment.Common.ContactInformation> EndListContactInformation(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<Mimosa.Apartment.Common.ContactInformation> _result = ((System.Collections.Generic.List<Mimosa.Apartment.Common.ContactInformation>)(base.EndInvoke("ListContactInformation", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSaveContactInformation(System.Collections.Generic.List<Mimosa.Apartment.Common.ContactInformation> saveList, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = saveList;
                System.IAsyncResult _result = base.BeginInvoke("SaveContactInformation", _args, callback, asyncState);
                return _result;
            }
            
            public void EndSaveContactInformation(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("SaveContactInformation", _args, result);
            }
            
            public System.IAsyncResult BeginListCustomer(System.Nullable<int> customerId, string name, bool includeLegacy, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = customerId;
                _args[1] = name;
                _args[2] = includeLegacy;
                System.IAsyncResult _result = base.BeginInvoke("ListCustomer", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<Mimosa.Apartment.Common.Customer> EndListCustomer(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<Mimosa.Apartment.Common.Customer> _result = ((System.Collections.Generic.List<Mimosa.Apartment.Common.Customer>)(base.EndInvoke("ListCustomer", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSaveCustomer(System.Collections.Generic.List<Mimosa.Apartment.Common.Customer> saveList, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = saveList;
                System.IAsyncResult _result = base.BeginInvoke("SaveCustomer", _args, callback, asyncState);
                return _result;
            }
            
            public void EndSaveCustomer(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("SaveCustomer", _args, result);
            }
        }
    }
}
