//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mimosa.Apartment.Silverlight.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringLibrary_VN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringLibrary_VN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mimosa.Apartment.Silverlight.UI.Resources.StringLibrary_VN", typeof(StringLibrary_VN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày Đặt.
        /// </summary>
        internal static string BookingAdmin_BookDate {
            get {
                return ResourceManager.GetString("BookingAdmin_BookDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng này đã được đặt hay thuê trong khoảng thời gian này. Hãy chọn phòng khác hay ngày khác..
        /// </summary>
        internal static string BookingAdmin_BookingExist {
            get {
                return ResourceManager.GetString("BookingAdmin_BookingExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hợp đồng.
        /// </summary>
        internal static string BookingAdmin_ContractDateSign {
            get {
                return ResourceManager.GetString("BookingAdmin_ContractDateSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá hợp đồng.
        /// </summary>
        internal static string BookingAdmin_ContractTotalPrice {
            get {
                return ResourceManager.GetString("BookingAdmin_ContractTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng 2.
        /// </summary>
        internal static string BookingAdmin_Customer2Name {
            get {
                return ResourceManager.GetString("BookingAdmin_Customer2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        internal static string BookingAdmin_CustomerName {
            get {
                return ResourceManager.GetString("BookingAdmin_CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin hãy nhập tên khách hàng.
        /// </summary>
        internal static string BookingAdmin_CustomerNotValid {
            get {
                return ResourceManager.GetString("BookingAdmin_CustomerNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng.
        /// </summary>
        internal static string BookingAdmin_RoomName {
            get {
                return ResourceManager.GetString("BookingAdmin_RoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin hãy chọn phòng.
        /// </summary>
        internal static string BookingAdmin_RoomNotValid {
            get {
                return ResourceManager.GetString("BookingAdmin_RoomNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá phòng.
        /// </summary>
        internal static string BookingAdmin_RoomPrice {
            get {
                return ResourceManager.GetString("BookingAdmin_RoomPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết khách hàng.
        /// </summary>
        internal static string BookingAdmin_uiPopupCustomer {
            get {
                return ResourceManager.GetString("BookingAdmin_uiPopupCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết thiết bị.
        /// </summary>
        internal static string BookingAdmin_uiPopupEquipmentDetails {
            get {
                return ResourceManager.GetString("BookingAdmin_uiPopupEquipmentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo đặt phòng.
        /// </summary>
        internal static string BookingAdmin_uiPopupNewBooking {
            get {
                return ResourceManager.GetString("BookingAdmin_uiPopupNewBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết dịch vụ.
        /// </summary>
        internal static string BookingAdmin_uiPopupServiceDetails {
            get {
                return ResourceManager.GetString("BookingAdmin_uiPopupServiceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt phòng / Hợp đồng.
        /// </summary>
        internal static string BookingAdmin_uiTitle {
            get {
                return ResourceManager.GetString("BookingAdmin_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái phòng.
        /// </summary>
        internal static string BookingAdminPage_lblBookingStatus {
            get {
                return ResourceManager.GetString("BookingAdminPage_lblBookingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        internal static string BookingAdminPage_lblCustomer {
            get {
                return ResourceManager.GetString("BookingAdminPage_lblCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        internal static string BookingAdminPage_lblFromDate {
            get {
                return ResourceManager.GetString("BookingAdminPage_lblFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        internal static string BookingAdminPage_lblToDate {
            get {
                return ResourceManager.GetString("BookingAdminPage_lblToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị đặt phòng.
        /// </summary>
        internal static string BookingAdminPage_uiTitle {
            get {
                return ResourceManager.GetString("BookingAdminPage_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đặt phòng :.
        /// </summary>
        internal static string BookingNew_uiTitle {
            get {
                return ResourceManager.GetString("BookingNew_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền đã thanh toán.
        /// </summary>
        internal static string BookingPaymentPage_CustomerPaid {
            get {
                return ResourceManager.GetString("BookingPaymentPage_CustomerPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá thiết bị.
        /// </summary>
        internal static string BookingPaymentPage_EquipmentPrice {
            get {
                return ResourceManager.GetString("BookingPaymentPage_EquipmentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền còn lại.
        /// </summary>
        internal static string BookingPaymentPage_MoneyLeft {
            get {
                return ResourceManager.GetString("BookingPaymentPage_MoneyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thanh toán.
        /// </summary>
        internal static string BookingPaymentPage_Payment {
            get {
                return ResourceManager.GetString("BookingPaymentPage_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        internal static string BookingPaymentPage_radAll {
            get {
                return ResourceManager.GetString("BookingPaymentPage_radAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa thanh toán.
        /// </summary>
        internal static string BookingPaymentPage_radNotPaid {
            get {
                return ResourceManager.GetString("BookingPaymentPage_radNotPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thanh toán.
        /// </summary>
        internal static string BookingPaymentPage_radPaid {
            get {
                return ResourceManager.GetString("BookingPaymentPage_radPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá phòng.
        /// </summary>
        internal static string BookingPaymentPage_RoomPrice {
            get {
                return ResourceManager.GetString("BookingPaymentPage_RoomPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá dịch vụ.
        /// </summary>
        internal static string BookingPaymentPage_ServicePrice {
            get {
                return ResourceManager.GetString("BookingPaymentPage_ServicePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng sổ tiền.
        /// </summary>
        internal static string BookingPaymentPage_TotalPrice {
            get {
                return ResourceManager.GetString("BookingPaymentPage_TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết thanh toán, từ ngày {0} đến ngày {1}.
        /// </summary>
        internal static string BookingPaymentPage_uiPopupPaymentDetails {
            get {
                return ResourceManager.GetString("BookingPaymentPage_uiPopupPaymentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán hàng tháng.
        /// </summary>
        internal static string BookingPaymentPage_uiTitle {
            get {
                return ResourceManager.GetString("BookingPaymentPage_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu.
        /// </summary>
        internal static string ChangePasswordPage_lblConfirmNewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordPage_lblConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        internal static string ChangePasswordPage_lblNewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordPage_lblNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string ChangePasswordPage_lblPassword {
            get {
                return ResourceManager.GetString("ChangePasswordPage_lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi mật khẩu.
        /// </summary>
        internal static string ChangePasswordPage_uiSubmitButton {
            get {
                return ResourceManager.GetString("ChangePasswordPage_uiSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đồi mật khẩu.
        /// </summary>
        internal static string ChangePasswordPage_uiTitle {
            get {
                return ResourceManager.GetString("ChangePasswordPage_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        internal static string Common_btnAdd {
            get {
                return ResourceManager.GetString("Common_btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string Common_btnCancel {
            get {
                return ResourceManager.GetString("Common_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Common_btnEmail {
            get {
                return ResourceManager.GetString("Common_btnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Common_btnExport {
            get {
                return ResourceManager.GetString("Common_btnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        internal static string Common_btnInsert {
            get {
                return ResourceManager.GetString("Common_btnInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới.
        /// </summary>
        internal static string Common_btnNew {
            get {
                return ResourceManager.GetString("Common_btnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Common_btnOK {
            get {
                return ResourceManager.GetString("Common_btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string Common_btnRemove {
            get {
                return ResourceManager.GetString("Common_btnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string Common_btnSave {
            get {
                return ResourceManager.GetString("Common_btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string Common_btnSearch {
            get {
                return ResourceManager.GetString("Common_btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy bỏ thay đổi.
        /// </summary>
        internal static string Common_ChangesCancelled {
            get {
                return ResourceManager.GetString("Common_ChangesCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị inactive.
        /// </summary>
        internal static string Common_chkShowLegacy {
            get {
                return ResourceManager.GetString("Common_chkShowLegacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu xác nhận.
        /// </summary>
        internal static string Common_ConfirmationRequired {
            get {
                return ResourceManager.GetString("Common_ConfirmationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa &apos;{0}&apos; không?.
        /// </summary>
        internal static string Common_ConfirmDelete {
            get {
                return ResourceManager.GetString("Common_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa không?.
        /// </summary>
        internal static string Common_ConfirmDeleteNoParam {
            get {
                return ResourceManager.GetString("Common_ConfirmDeleteNoParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tải dữ liệu.
        /// </summary>
        internal static string Common_DataLoading {
            get {
                return ResourceManager.GetString("Common_DataLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu cho những lựa chọn này.
        /// </summary>
        internal static string Common_DataNotFound {
            get {
                return ResourceManager.GetString("Common_DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không được tải.
        /// </summary>
        internal static string Common_DataNotLoaded {
            get {
                return ResourceManager.GetString("Common_DataNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có sự giao nhau giữa những khoảng thời gian.
        /// </summary>
        internal static string Common_DateIntersect {
            get {
                return ResourceManager.GetString("Common_DateIntersect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày kết thúc phải lớn hơn ngày bắt đầu.
        /// </summary>
        internal static string Common_DateNotValid {
            get {
                return ResourceManager.GetString("Common_DateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; không thể bị xóa.
        /// </summary>
        internal static string Common_DeleteFailed {
            get {
                return ResourceManager.GetString("Common_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; không thể bị xóa. Đang được sử dụng..
        /// </summary>
        internal static string Common_DeleteFailedBeingUsed {
            get {
                return ResourceManager.GetString("Common_DeleteFailedBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        internal static string Common_Description {
            get {
                return ResourceManager.GetString("Common_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã được gửi..
        /// </summary>
        internal static string Common_EmailSent {
            get {
                return ResourceManager.GetString("Common_EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ.
        /// </summary>
        internal static string Common_From {
            get {
                return ResourceManager.GetString("Common_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string Common_Inactive {
            get {
                return ResourceManager.GetString("Common_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị này đã tồn tại.
        /// </summary>
        internal static string Common_ItemExist {
            get {
                return ResourceManager.GetString("Common_ItemExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        internal static string Common_lblDetail {
            get {
                return ResourceManager.GetString("Common_lblDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tòa nhà.
        /// </summary>
        internal static string Common_lblSite {
            get {
                return ResourceManager.GetString("Common_lblSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được vượt quá 123 kí tự.
        /// </summary>
        internal static string Common_NameLengthErrorMessage {
            get {
                return ResourceManager.GetString("Common_NameLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tao mới.
        /// </summary>
        internal static string Common_NewRecord {
            get {
                return ResourceManager.GetString("Common_NewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không được phép xem trang này.
        /// </summary>
        internal static string Common_NoPermission {
            get {
                return ResourceManager.GetString("Common_NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hành động không thành công.
        /// </summary>
        internal static string Common_OperationFailed {
            get {
                return ResourceManager.GetString("Common_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi đã được lưu.
        /// </summary>
        internal static string Common_RecordsSaved {
            get {
                return ResourceManager.GetString("Common_RecordsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; là dữ liệu bắt buộc..
        /// </summary>
        internal static string Common_RequiredField {
            get {
                return ResourceManager.GetString("Common_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đây là dữ liệu bắt buộc phải nhập..
        /// </summary>
        internal static string Common_RequiredFieldGeneric {
            get {
                return ResourceManager.GetString("Common_RequiredFieldGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; vừa được lưu...
        /// </summary>
        internal static string Common_SaveComplete {
            get {
                return ResourceManager.GetString("Common_SaveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tới.
        /// </summary>
        internal static string Common_To {
            get {
                return ResourceManager.GetString("Common_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi kiểm tra.
        /// </summary>
        internal static string Common_ValidationError {
            get {
                return ResourceManager.GetString("Common_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string ContactInformationPanel_lblAddress {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ 2.
        /// </summary>
        internal static string ContactInformationPanel_lblAddress2 {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành phố.
        /// </summary>
        internal static string ContactInformationPanel_lblCity {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quốc gia.
        /// </summary>
        internal static string ContactInformationPanel_lblCountry {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        internal static string ContactInformationPanel_lblDateOfBirth {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quận.
        /// </summary>
        internal static string ContactInformationPanel_lblDistrict {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string ContactInformationPanel_lblEmail {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string ContactInformationPanel_lblFax {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string ContactInformationPanel_lblFirstName {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ.
        /// </summary>
        internal static string ContactInformationPanel_lblLastName {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string ContactInformationPanel_lblPhone {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vùng.
        /// </summary>
        internal static string ContactInformationPanel_lblPostCode {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bang.
        /// </summary>
        internal static string ContactInformationPanel_lblState {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa.
        /// </summary>
        internal static string ContactInformationPanel_lblVisa {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa hợp lệ.
        /// </summary>
        internal static string ContactInformationPanel_lblVisaValid {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblVisaValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin liên lạc.
        /// </summary>
        internal static string ContactInformationPanel_txtContactInfo {
            get {
                return ResourceManager.GetString("ContactInformationPanel_txtContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có hợp đồng tại tòa nhà :.
        /// </summary>
        internal static string CustomerAdminPage_chkHasContract {
            get {
                return ResourceManager.GetString("CustomerAdminPage_chkHasContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị khách hàng.
        /// </summary>
        internal static string CustomerAdminPage_uiTitle {
            get {
                return ResourceManager.GetString("CustomerAdminPage_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin hãy nhập tên khách hàng.
        /// </summary>
        internal static string CustomerDetails_CustomerNotValid {
            get {
                return ResourceManager.GetString("CustomerDetails_CustomerNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuổi.
        /// </summary>
        internal static string CustomerDetails_lblAge {
            get {
                return ResourceManager.GetString("CustomerDetails_lblAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        internal static string CustomerDetails_lblCustomerTitle {
            get {
                return ResourceManager.GetString("CustomerDetails_lblCustomerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giời tính.
        /// </summary>
        internal static string CustomerDetails_lblGender {
            get {
                return ResourceManager.GetString("CustomerDetails_lblGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        internal static string CustomerDetails_radFemale {
            get {
                return ResourceManager.GetString("CustomerDetails_radFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        internal static string CustomerDetails_radMale {
            get {
                return ResourceManager.GetString("CustomerDetails_radMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin hãy chọn phòng.
        /// </summary>
        internal static string CustomerDetails_RoomNotValid {
            get {
                return ResourceManager.GetString("CustomerDetails_RoomNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        internal static string EquipmentAdminPage_Description {
            get {
                return ResourceManager.GetString("EquipmentAdminPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thiết bị.
        /// </summary>
        internal static string EquipmentAdminPage_EquipmentName {
            get {
                return ResourceManager.GetString("EquipmentAdminPage_EquipmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string EquipmentAdminPage_Inactive {
            get {
                return ResourceManager.GetString("EquipmentAdminPage_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi phí.
        /// </summary>
        internal static string EquipmentAdminPage_RealPrice {
            get {
                return ResourceManager.GetString("EquipmentAdminPage_RealPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        internal static string EquipmentAdminPage_RentPrice {
            get {
                return ResourceManager.GetString("EquipmentAdminPage_RentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị thiết bị.
        /// </summary>
        internal static string EquipmentAdminPage_uiTitle {
            get {
                return ResourceManager.GetString("EquipmentAdminPage_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        internal static string EquipmentAdminPage_Unit {
            get {
                return ResourceManager.GetString("EquipmentAdminPage_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        internal static string ImageItem_lblDescription {
            get {
                return ResourceManager.GetString("ImageItem_lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số thứ tự.
        /// </summary>
        internal static string ImageItem_lblDisplayIndex {
            get {
                return ResourceManager.GetString("ImageItem_lblDisplayIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string ImageItem_lblName {
            get {
                return ResourceManager.GetString("ImageItem_lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn.
        /// </summary>
        internal static string ImageUpload_btnChooseImage {
            get {
                return ResourceManager.GetString("ImageUpload_btnChooseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        internal static string ImageUpload_lblPhoto {
            get {
                return ResourceManager.GetString("ImageUpload_lblPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        internal static string ImageUpload_lblTitle {
            get {
                return ResourceManager.GetString("ImageUpload_lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải hình.
        /// </summary>
        internal static string ImageUpload_uiPopupUpload {
            get {
                return ResourceManager.GetString("ImageUpload_uiPopupUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có tên trùng với tên nhập. Hãy nhập lại..
        /// </summary>
        internal static string RoleAdminPage_DuplicatedName {
            get {
                return ResourceManager.GetString("RoleAdminPage_DuplicatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên quyền.
        /// </summary>
        internal static string RoleAdminPage_RoleName {
            get {
                return ResourceManager.GetString("RoleAdminPage_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị quyền.
        /// </summary>
        internal static string RoleAdminPage_uiTitle {
            get {
                return ResourceManager.GetString("RoleAdminPage_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quền.
        /// </summary>
        internal static string RoleComponentAdminPage_lblRole {
            get {
                return ResourceManager.GetString("RoleComponentAdminPage_lblRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người có quyền này :.
        /// </summary>
        internal static string RoleComponentAdminPage_lblUserHasRole {
            get {
                return ResourceManager.GetString("RoleComponentAdminPage_lblUserHasRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền truy xuất trang.
        /// </summary>
        internal static string RoleComponentAdminPage_uiTitle {
            get {
                return ResourceManager.GetString("RoleComponentAdminPage_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá phòng.
        /// </summary>
        internal static string RoomAdminPage_BasePrice {
            get {
                return ResourceManager.GetString("RoomAdminPage_BasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string RoomAdminPage_chkAvailable {
            get {
                return ResourceManager.GetString("RoomAdminPage_chkAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupied.
        /// </summary>
        internal static string RoomAdminPage_chkOccupied {
            get {
                return ResourceManager.GetString("RoomAdminPage_chkOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiều Dài.
        /// </summary>
        internal static string RoomAdminPage_Height {
            get {
                return ResourceManager.GetString("RoomAdminPage_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string RoomAdminPage_Inactive {
            get {
                return ResourceManager.GetString("RoomAdminPage_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lầu.
        /// </summary>
        internal static string RoomAdminPage_lblFloor {
            get {
                return ResourceManager.GetString("RoomAdminPage_lblFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phòng.
        /// </summary>
        internal static string RoomAdminPage_lblName {
            get {
                return ResourceManager.GetString("RoomAdminPage_lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái phòng.
        /// </summary>
        internal static string RoomAdminPage_lblRoomStatus {
            get {
                return ResourceManager.GetString("RoomAdminPage_lblRoomStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu phòng.
        /// </summary>
        internal static string RoomAdminPage_lblRoomType {
            get {
                return ResourceManager.GetString("RoomAdminPage_lblRoomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mét vuông.
        /// </summary>
        internal static string RoomAdminPage_MeterSquare {
            get {
                return ResourceManager.GetString("RoomAdminPage_MeterSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị phòng.
        /// </summary>
        internal static string RoomAdminPage_uiTitle {
            get {
                return ResourceManager.GetString("RoomAdminPage_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiều rộng.
        /// </summary>
        internal static string RoomAdminPage_Width {
            get {
                return ResourceManager.GetString("RoomAdminPage_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        internal static string ServiceAdminPage_Description {
            get {
                return ResourceManager.GetString("ServiceAdminPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string ServiceAdminPage_Inactive {
            get {
                return ResourceManager.GetString("ServiceAdminPage_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        internal static string ServiceAdminPage_Price {
            get {
                return ResourceManager.GetString("ServiceAdminPage_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên dịch vụ.
        /// </summary>
        internal static string ServiceAdminPage_ServiceName {
            get {
                return ResourceManager.GetString("ServiceAdminPage_ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị dịch vụ.
        /// </summary>
        internal static string ServiceAdminPage_uiTitle {
            get {
                return ResourceManager.GetString("ServiceAdminPage_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        internal static string ServiceAdminPage_Unit {
            get {
                return ResourceManager.GetString("ServiceAdminPage_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tắt.
        /// </summary>
        internal static string SiteAdminPage_AbbreviatedName {
            get {
                return ResourceManager.GetString("SiteAdminPage_AbbreviatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số thứ tự.
        /// </summary>
        internal static string SiteAdminPage_DisplayIndex {
            get {
                return ResourceManager.GetString("SiteAdminPage_DisplayIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string SiteAdminPage_Inactive {
            get {
                return ResourceManager.GetString("SiteAdminPage_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Key.
        /// </summary>
        internal static string SiteAdminPage_LicenseKey {
            get {
                return ResourceManager.GetString("SiteAdminPage_LicenseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string SiteAdminPage_Name {
            get {
                return ResourceManager.GetString("SiteAdminPage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số sao.
        /// </summary>
        internal static string SiteAdminPage_StarRating {
            get {
                return ResourceManager.GetString("SiteAdminPage_StarRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị tòa nhà.
        /// </summary>
        internal static string SiteAdminPage_uiTitle {
            get {
                return ResourceManager.GetString("SiteAdminPage_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có tên trùng với tên nhập. Hãy nhập lại..
        /// </summary>
        internal static string SiteGroupAdminPage_DuplicatedName {
            get {
                return ResourceManager.GetString("SiteGroupAdminPage_DuplicatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toà nhà.
        /// </summary>
        internal static string SiteGroupAdminPage_Site {
            get {
                return ResourceManager.GetString("SiteGroupAdminPage_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tòa nhà đã tồn tại.
        /// </summary>
        internal static string SiteGroupAdminPage_SiteAlreadyExist {
            get {
                return ResourceManager.GetString("SiteGroupAdminPage_SiteAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm tòa nhà.
        /// </summary>
        internal static string SiteGroupAdminPage_SiteGroup {
            get {
                return ResourceManager.GetString("SiteGroupAdminPage_SiteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị nhóm tòa nhà.
        /// </summary>
        internal static string SiteGroupAdminPage_uiTitle {
            get {
                return ResourceManager.GetString("SiteGroupAdminPage_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mở khóa.
        /// </summary>
        internal static string UserAccount_btnUnlock {
            get {
                return ResourceManager.GetString("UserAccount_btnUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản được duyệt.
        /// </summary>
        internal static string UserAccount_chkAccountApproved {
            get {
                return ResourceManager.GetString("UserAccount_chkAccountApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi câu hỏi và trả lời bảo mật.
        /// </summary>
        internal static string UserAccount_chkChangePasswordQuestionAnswer {
            get {
                return ResourceManager.GetString("UserAccount_chkChangePasswordQuestionAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset mật khẩu.
        /// </summary>
        internal static string UserAccount_chkResetPassword {
            get {
                return ResourceManager.GetString("UserAccount_chkResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tạo {0}, cập nhật gần nhất {1}..
        /// </summary>
        internal static string UserAccount_CreatedInfo {
            get {
                return ResourceManager.GetString("UserAccount_CreatedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa được nhập.
        /// </summary>
        internal static string UserAccount_DefaultPasswordAnswer {
            get {
                return ResourceManager.GetString("UserAccount_DefaultPasswordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa được nhập.
        /// </summary>
        internal static string UserAccount_DefaultPasswordQuestion {
            get {
                return ResourceManager.GetString("UserAccount_DefaultPasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy nhập mật khẩu để thay  đổi câu hỏi và trả lời bảo mật.
        /// </summary>
        internal static string UserAccount_InputPasswordEmpty {
            get {
                return ResourceManager.GetString("UserAccount_InputPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thay  đổi câu hỏi và trả lời bảo mật vì mật khẩu không đúng.
        /// </summary>
        internal static string UserAccount_InputPasswordIncorrect {
            get {
                return ResourceManager.GetString("UserAccount_InputPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string UserAccount_lblEmail {
            get {
                return ResourceManager.GetString("UserAccount_lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string UserAccount_lblInputPassword {
            get {
                return ResourceManager.GetString("UserAccount_lblInputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string UserAccount_lblPassword {
            get {
                return ResourceManager.GetString("UserAccount_lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản.
        /// </summary>
        internal static string UserAccount_lblUsername {
            get {
                return ResourceManager.GetString("UserAccount_lblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản bị khóa lúc {0}. Hãy xóa đánh dấu và ấn nút Lưu để mở khóa tài khoản..
        /// </summary>
        internal static string UserAccount_LockedOutMessage {
            get {
                return ResourceManager.GetString("UserAccount_LockedOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới là &apos;{0}&apos;, hãy thông báo cho người dùng.
        /// </summary>
        internal static string UserAccount_NewGenPassword {
            get {
                return ResourceManager.GetString("UserAccount_NewGenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản mới.
        /// </summary>
        internal static string UserAccount_NewRecord {
            get {
                return ResourceManager.GetString("UserAccount_NewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng hiện đang offline.
        /// </summary>
        internal static string UserAccount_OfflineTooltip {
            get {
                return ResourceManager.GetString("UserAccount_OfflineTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng hiện đang online..
        /// </summary>
        internal static string UserAccount_OnlineTooltip {
            get {
                return ResourceManager.GetString("UserAccount_OnlineTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy nhập câu hỏi và trả lời bảo mật.
        /// </summary>
        internal static string UserAccount_QuestionPasswordEmpty {
            get {
                return ResourceManager.GetString("UserAccount_QuestionPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu trả lời bảo mật.
        /// </summary>
        internal static string UserAccount_txtPasswordAnswerLabel {
            get {
                return ResourceManager.GetString("UserAccount_txtPasswordAnswerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu hỏi bảo mật.
        /// </summary>
        internal static string UserAccount_txtPasswordQuestionLabel {
            get {
                return ResourceManager.GetString("UserAccount_txtPasswordQuestionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên và mật khẩu không được trống.
        /// </summary>
        internal static string UserAccount_UserPasswordEmpty {
            get {
                return ResourceManager.GetString("UserAccount_UserPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản vừa được mở khóa.
        /// </summary>
        internal static string UserAccount_UserUnlocked {
            get {
                return ResourceManager.GetString("UserAccount_UserUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        internal static string UserAccountPage_uiTitle {
            get {
                return ResourceManager.GetString("UserAccountPage_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền.
        /// </summary>
        internal static string UserRoleAuthAdminPage_lblRole {
            get {
                return ResourceManager.GetString("UserRoleAuthAdminPage_lblRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm Tòa Nhà.
        /// </summary>
        internal static string UserRoleAuthAdminPage_lblSiteGroup {
            get {
                return ResourceManager.GetString("UserRoleAuthAdminPage_lblSiteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng.
        /// </summary>
        internal static string UserRoleAuthAdminPage_lblUser {
            get {
                return ResourceManager.GetString("UserRoleAuthAdminPage_lblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang.
        /// </summary>
        internal static string UserRoleAuthAdminPage_uiTabComponents {
            get {
                return ResourceManager.GetString("UserRoleAuthAdminPage_uiTabComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền.
        /// </summary>
        internal static string UserRoleAuthAdminPage_uiTabRoles {
            get {
                return ResourceManager.GetString("UserRoleAuthAdminPage_uiTabRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền người dùng.
        /// </summary>
        internal static string UserRoleAuthAdminPage_uiTitle {
            get {
                return ResourceManager.GetString("UserRoleAuthAdminPage_uiTitle", resourceCulture);
            }
        }
    }
}
