//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mimosa.Apartment.Silverlight.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringLibrary_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringLibrary_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mimosa.Apartment.Silverlight.UI.Resources.StringLibrary_EN", typeof(StringLibrary_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Date.
        /// </summary>
        internal static string BookingAdmin_BookDate {
            get {
                return ResourceManager.GetString("BookingAdmin_BookDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This room was booked/rented in that period. Please choose other room or date range.
        /// </summary>
        internal static string BookingAdmin_BookingExist {
            get {
                return ResourceManager.GetString("BookingAdmin_BookingExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Date.
        /// </summary>
        internal static string BookingAdmin_ContractDateSign {
            get {
                return ResourceManager.GetString("BookingAdmin_ContractDateSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Price.
        /// </summary>
        internal static string BookingAdmin_ContractTotalPrice {
            get {
                return ResourceManager.GetString("BookingAdmin_ContractTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer 2.
        /// </summary>
        internal static string BookingAdmin_Customer2Name {
            get {
                return ResourceManager.GetString("BookingAdmin_Customer2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string BookingAdmin_CustomerName {
            get {
                return ResourceManager.GetString("BookingAdmin_CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input customer&apos;s name.
        /// </summary>
        internal static string BookingAdmin_CustomerNotValid {
            get {
                return ResourceManager.GetString("BookingAdmin_CustomerNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string BookingAdmin_RoomName {
            get {
                return ResourceManager.GetString("BookingAdmin_RoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a specific room.
        /// </summary>
        internal static string BookingAdmin_RoomNotValid {
            get {
                return ResourceManager.GetString("BookingAdmin_RoomNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Price.
        /// </summary>
        internal static string BookingAdmin_RoomPrice {
            get {
                return ResourceManager.GetString("BookingAdmin_RoomPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Details.
        /// </summary>
        internal static string BookingAdmin_uiPopupCustomer {
            get {
                return ResourceManager.GetString("BookingAdmin_uiPopupCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Details.
        /// </summary>
        internal static string BookingAdmin_uiPopupEquipmentDetails {
            get {
                return ResourceManager.GetString("BookingAdmin_uiPopupEquipmentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Booking.
        /// </summary>
        internal static string BookingAdmin_uiPopupNewBooking {
            get {
                return ResourceManager.GetString("BookingAdmin_uiPopupNewBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Details.
        /// </summary>
        internal static string BookingAdmin_uiPopupServiceDetails {
            get {
                return ResourceManager.GetString("BookingAdmin_uiPopupServiceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookings / Contracts.
        /// </summary>
        internal static string BookingAdmin_uiTitle {
            get {
                return ResourceManager.GetString("BookingAdmin_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Status.
        /// </summary>
        internal static string BookingAdminPage_lblBookingStatus {
            get {
                return ResourceManager.GetString("BookingAdminPage_lblBookingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string BookingAdminPage_lblCustomer {
            get {
                return ResourceManager.GetString("BookingAdminPage_lblCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string BookingAdminPage_lblFromDate {
            get {
                return ResourceManager.GetString("BookingAdminPage_lblFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        internal static string BookingAdminPage_lblToDate {
            get {
                return ResourceManager.GetString("BookingAdminPage_lblToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Administration.
        /// </summary>
        internal static string BookingAdminPage_uiTitle {
            get {
                return ResourceManager.GetString("BookingAdminPage_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Info :.
        /// </summary>
        internal static string BookingNew_uiTitle {
            get {
                return ResourceManager.GetString("BookingNew_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Paid.
        /// </summary>
        internal static string BookingPaymentPage_CustomerPaid {
            get {
                return ResourceManager.GetString("BookingPaymentPage_CustomerPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Price.
        /// </summary>
        internal static string BookingPaymentPage_EquipmentPrice {
            get {
                return ResourceManager.GetString("BookingPaymentPage_EquipmentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Left.
        /// </summary>
        internal static string BookingPaymentPage_MoneyLeft {
            get {
                return ResourceManager.GetString("BookingPaymentPage_MoneyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string BookingPaymentPage_Payment {
            get {
                return ResourceManager.GetString("BookingPaymentPage_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string BookingPaymentPage_radAll {
            get {
                return ResourceManager.GetString("BookingPaymentPage_radAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Paid.
        /// </summary>
        internal static string BookingPaymentPage_radNotPaid {
            get {
                return ResourceManager.GetString("BookingPaymentPage_radNotPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        internal static string BookingPaymentPage_radPaid {
            get {
                return ResourceManager.GetString("BookingPaymentPage_radPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Price.
        /// </summary>
        internal static string BookingPaymentPage_RoomPrice {
            get {
                return ResourceManager.GetString("BookingPaymentPage_RoomPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Price.
        /// </summary>
        internal static string BookingPaymentPage_ServicePrice {
            get {
                return ResourceManager.GetString("BookingPaymentPage_ServicePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        internal static string BookingPaymentPage_TotalPrice {
            get {
                return ResourceManager.GetString("BookingPaymentPage_TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Details, from {0} to {1}.
        /// </summary>
        internal static string BookingPaymentPage_uiPopupPaymentDetails {
            get {
                return ResourceManager.GetString("BookingPaymentPage_uiPopupPaymentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Payment.
        /// </summary>
        internal static string BookingPaymentPage_uiTitle {
            get {
                return ResourceManager.GetString("BookingPaymentPage_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        internal static string ChangePasswordPage_lblConfirmNewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordPage_lblConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string ChangePasswordPage_lblNewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordPage_lblNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string ChangePasswordPage_lblPassword {
            get {
                return ResourceManager.GetString("ChangePasswordPage_lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePasswordPage_uiSubmitButton {
            get {
                return ResourceManager.GetString("ChangePasswordPage_uiSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePasswordPage_uiTitle {
            get {
                return ResourceManager.GetString("ChangePasswordPage_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Common_btnAdd {
            get {
                return ResourceManager.GetString("Common_btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Common_btnCancel {
            get {
                return ResourceManager.GetString("Common_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Common_btnEmail {
            get {
                return ResourceManager.GetString("Common_btnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Common_btnExport {
            get {
                return ResourceManager.GetString("Common_btnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string Common_btnInsert {
            get {
                return ResourceManager.GetString("Common_btnInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string Common_btnNew {
            get {
                return ResourceManager.GetString("Common_btnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Common_btnOK {
            get {
                return ResourceManager.GetString("Common_btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Common_btnRemove {
            get {
                return ResourceManager.GetString("Common_btnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Common_btnSave {
            get {
                return ResourceManager.GetString("Common_btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Common_btnSearch {
            get {
                return ResourceManager.GetString("Common_btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes cancelled:.
        /// </summary>
        internal static string Common_ChangesCancelled {
            get {
                return ResourceManager.GetString("Common_ChangesCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Inactive.
        /// </summary>
        internal static string Common_chkShowLegacy {
            get {
                return ResourceManager.GetString("Common_chkShowLegacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Required.
        /// </summary>
        internal static string Common_ConfirmationRequired {
            get {
                return ResourceManager.GetString("Common_ConfirmationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &apos;{0}&apos;?.
        /// </summary>
        internal static string Common_ConfirmDelete {
            get {
                return ResourceManager.GetString("Common_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        internal static string Common_ConfirmDeleteNoParam {
            get {
                return ResourceManager.GetString("Common_ConfirmDeleteNoParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacting server for data....
        /// </summary>
        internal static string Common_DataLoading {
            get {
                return ResourceManager.GetString("Common_DataLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data was found for the given options.
        /// </summary>
        internal static string Common_DataNotFound {
            get {
                return ResourceManager.GetString("Common_DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is not loaded.
        /// </summary>
        internal static string Common_DataNotLoaded {
            get {
                return ResourceManager.GetString("Common_DataNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an intersect between date ranges.
        /// </summary>
        internal static string Common_DateIntersect {
            get {
                return ResourceManager.GetString("Common_DateIntersect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date End must be greater than Date Start.
        /// </summary>
        internal static string Common_DateNotValid {
            get {
                return ResourceManager.GetString("Common_DateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; could not be deleted..
        /// </summary>
        internal static string Common_DeleteFailed {
            get {
                return ResourceManager.GetString("Common_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; could not be deleted. It is being used..
        /// </summary>
        internal static string Common_DeleteFailedBeingUsed {
            get {
                return ResourceManager.GetString("Common_DeleteFailedBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Common_Description {
            get {
                return ResourceManager.GetString("Common_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails sent:.
        /// </summary>
        internal static string Common_EmailSent {
            get {
                return ResourceManager.GetString("Common_EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string Common_From {
            get {
                return ResourceManager.GetString("Common_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string Common_Inactive {
            get {
                return ResourceManager.GetString("Common_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is already exist.
        /// </summary>
        internal static string Common_ItemExist {
            get {
                return ResourceManager.GetString("Common_ItemExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Common_lblDetail {
            get {
                return ResourceManager.GetString("Common_lblDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string Common_lblSite {
            get {
                return ResourceManager.GetString("Common_lblSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string may not exceed 128 characters in length..
        /// </summary>
        internal static string Common_NameLengthErrorMessage {
            get {
                return ResourceManager.GetString("Common_NameLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Record..
        /// </summary>
        internal static string Common_NewRecord {
            get {
                return ResourceManager.GetString("Common_NewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to view this area.
        /// </summary>
        internal static string Common_NoPermission {
            get {
                return ResourceManager.GetString("Common_NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Failed.
        /// </summary>
        internal static string Common_OperationFailed {
            get {
                return ResourceManager.GetString("Common_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved:.
        /// </summary>
        internal static string Common_RecordsSaved {
            get {
                return ResourceManager.GetString("Common_RecordsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a required field..
        /// </summary>
        internal static string Common_RequiredField {
            get {
                return ResourceManager.GetString("Common_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a required field..
        /// </summary>
        internal static string Common_RequiredFieldGeneric {
            get {
                return ResourceManager.GetString("Common_RequiredFieldGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has been saved..
        /// </summary>
        internal static string Common_SaveComplete {
            get {
                return ResourceManager.GetString("Common_SaveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string Common_To {
            get {
                return ResourceManager.GetString("Common_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        internal static string Common_ValidationError {
            get {
                return ResourceManager.GetString("Common_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string ContactInformationPanel_lblAddress {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        internal static string ContactInformationPanel_lblAddress2 {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string ContactInformationPanel_lblCity {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string ContactInformationPanel_lblCountry {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string ContactInformationPanel_lblDateOfBirth {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string ContactInformationPanel_lblDistrict {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string ContactInformationPanel_lblEmail {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string ContactInformationPanel_lblFax {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string ContactInformationPanel_lblFirstName {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string ContactInformationPanel_lblLastName {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string ContactInformationPanel_lblPhone {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code.
        /// </summary>
        internal static string ContactInformationPanel_lblPostCode {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string ContactInformationPanel_lblState {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa.
        /// </summary>
        internal static string ContactInformationPanel_lblVisa {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Valid.
        /// </summary>
        internal static string ContactInformationPanel_lblVisaValid {
            get {
                return ResourceManager.GetString("ContactInformationPanel_lblVisaValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        internal static string ContactInformationPanel_txtContactInfo {
            get {
                return ResourceManager.GetString("ContactInformationPanel_txtContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Contract in Site :.
        /// </summary>
        internal static string CustomerAdminPage_chkHasContract {
            get {
                return ResourceManager.GetString("CustomerAdminPage_chkHasContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Administration.
        /// </summary>
        internal static string CustomerAdminPage_uiTitle {
            get {
                return ResourceManager.GetString("CustomerAdminPage_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input customer&apos;s name.
        /// </summary>
        internal static string CustomerDetails_CustomerNotValid {
            get {
                return ResourceManager.GetString("CustomerDetails_CustomerNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string CustomerDetails_lblAge {
            get {
                return ResourceManager.GetString("CustomerDetails_lblAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string CustomerDetails_lblCustomerTitle {
            get {
                return ResourceManager.GetString("CustomerDetails_lblCustomerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string CustomerDetails_lblGender {
            get {
                return ResourceManager.GetString("CustomerDetails_lblGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string CustomerDetails_radFemale {
            get {
                return ResourceManager.GetString("CustomerDetails_radFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string CustomerDetails_radMale {
            get {
                return ResourceManager.GetString("CustomerDetails_radMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a specific room.
        /// </summary>
        internal static string CustomerDetails_RoomNotValid {
            get {
                return ResourceManager.GetString("CustomerDetails_RoomNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string EquipmentAdminPage_Description {
            get {
                return ResourceManager.GetString("EquipmentAdminPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Name.
        /// </summary>
        internal static string EquipmentAdminPage_EquipmentName {
            get {
                return ResourceManager.GetString("EquipmentAdminPage_EquipmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string EquipmentAdminPage_Inactive {
            get {
                return ResourceManager.GetString("EquipmentAdminPage_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string EquipmentAdminPage_RealPrice {
            get {
                return ResourceManager.GetString("EquipmentAdminPage_RealPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string EquipmentAdminPage_RentPrice {
            get {
                return ResourceManager.GetString("EquipmentAdminPage_RentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Administration.
        /// </summary>
        internal static string EquipmentAdminPage_uiTitle {
            get {
                return ResourceManager.GetString("EquipmentAdminPage_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string EquipmentAdminPage_Unit {
            get {
                return ResourceManager.GetString("EquipmentAdminPage_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ImageItem_lblDescription {
            get {
                return ResourceManager.GetString("ImageItem_lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Index.
        /// </summary>
        internal static string ImageItem_lblDisplayIndex {
            get {
                return ResourceManager.GetString("ImageItem_lblDisplayIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ImageItem_lblName {
            get {
                return ResourceManager.GetString("ImageItem_lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string ImageUpload_btnChooseImage {
            get {
                return ResourceManager.GetString("ImageUpload_btnChooseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        internal static string ImageUpload_lblPhoto {
            get {
                return ResourceManager.GetString("ImageUpload_lblPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string ImageUpload_lblTitle {
            get {
                return ResourceManager.GetString("ImageUpload_lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Images.
        /// </summary>
        internal static string ImageUpload_uiPopupUpload {
            get {
                return ResourceManager.GetString("ImageUpload_uiPopupUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are duplicated name. Please check again..
        /// </summary>
        internal static string RoleAdminPage_DuplicatedName {
            get {
                return ResourceManager.GetString("RoleAdminPage_DuplicatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        internal static string RoleAdminPage_RoleName {
            get {
                return ResourceManager.GetString("RoleAdminPage_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Administrattion.
        /// </summary>
        internal static string RoleAdminPage_uiTitle {
            get {
                return ResourceManager.GetString("RoleAdminPage_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string RoleComponentAdminPage_lblRole {
            get {
                return ResourceManager.GetString("RoleComponentAdminPage_lblRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users that have this role :.
        /// </summary>
        internal static string RoleComponentAdminPage_lblUserHasRole {
            get {
                return ResourceManager.GetString("RoleComponentAdminPage_lblUserHasRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Component Permission.
        /// </summary>
        internal static string RoleComponentAdminPage_uiTitle {
            get {
                return ResourceManager.GetString("RoleComponentAdminPage_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Price.
        /// </summary>
        internal static string RoomAdminPage_BasePrice {
            get {
                return ResourceManager.GetString("RoomAdminPage_BasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string RoomAdminPage_chkAvailable {
            get {
                return ResourceManager.GetString("RoomAdminPage_chkAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupied.
        /// </summary>
        internal static string RoomAdminPage_chkOccupied {
            get {
                return ResourceManager.GetString("RoomAdminPage_chkOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string RoomAdminPage_Height {
            get {
                return ResourceManager.GetString("RoomAdminPage_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string RoomAdminPage_Inactive {
            get {
                return ResourceManager.GetString("RoomAdminPage_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        internal static string RoomAdminPage_lblFloor {
            get {
                return ResourceManager.GetString("RoomAdminPage_lblFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string RoomAdminPage_lblName {
            get {
                return ResourceManager.GetString("RoomAdminPage_lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Status.
        /// </summary>
        internal static string RoomAdminPage_lblRoomStatus {
            get {
                return ResourceManager.GetString("RoomAdminPage_lblRoomStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Type.
        /// </summary>
        internal static string RoomAdminPage_lblRoomType {
            get {
                return ResourceManager.GetString("RoomAdminPage_lblRoomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Square.
        /// </summary>
        internal static string RoomAdminPage_MeterSquare {
            get {
                return ResourceManager.GetString("RoomAdminPage_MeterSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Administration.
        /// </summary>
        internal static string RoomAdminPage_uiTitle {
            get {
                return ResourceManager.GetString("RoomAdminPage_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string RoomAdminPage_Width {
            get {
                return ResourceManager.GetString("RoomAdminPage_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ServiceAdminPage_Description {
            get {
                return ResourceManager.GetString("ServiceAdminPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string ServiceAdminPage_Inactive {
            get {
                return ResourceManager.GetString("ServiceAdminPage_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string ServiceAdminPage_Price {
            get {
                return ResourceManager.GetString("ServiceAdminPage_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        internal static string ServiceAdminPage_ServiceName {
            get {
                return ResourceManager.GetString("ServiceAdminPage_ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Administration.
        /// </summary>
        internal static string ServiceAdminPage_uiTitle {
            get {
                return ResourceManager.GetString("ServiceAdminPage_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string ServiceAdminPage_Unit {
            get {
                return ResourceManager.GetString("ServiceAdminPage_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbr. Name.
        /// </summary>
        internal static string SiteAdminPage_AbbreviatedName {
            get {
                return ResourceManager.GetString("SiteAdminPage_AbbreviatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Index.
        /// </summary>
        internal static string SiteAdminPage_DisplayIndex {
            get {
                return ResourceManager.GetString("SiteAdminPage_DisplayIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string SiteAdminPage_Inactive {
            get {
                return ResourceManager.GetString("SiteAdminPage_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Key.
        /// </summary>
        internal static string SiteAdminPage_LicenseKey {
            get {
                return ResourceManager.GetString("SiteAdminPage_LicenseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SiteAdminPage_Name {
            get {
                return ResourceManager.GetString("SiteAdminPage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Rating.
        /// </summary>
        internal static string SiteAdminPage_StarRating {
            get {
                return ResourceManager.GetString("SiteAdminPage_StarRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Administration.
        /// </summary>
        internal static string SiteAdminPage_uiTitle {
            get {
                return ResourceManager.GetString("SiteAdminPage_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are duplicated name. Please check again..
        /// </summary>
        internal static string SiteGroupAdminPage_DuplicatedName {
            get {
                return ResourceManager.GetString("SiteGroupAdminPage_DuplicatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string SiteGroupAdminPage_Site {
            get {
                return ResourceManager.GetString("SiteGroupAdminPage_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This site is already added.
        /// </summary>
        internal static string SiteGroupAdminPage_SiteAlreadyExist {
            get {
                return ResourceManager.GetString("SiteGroupAdminPage_SiteAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Group.
        /// </summary>
        internal static string SiteGroupAdminPage_SiteGroup {
            get {
                return ResourceManager.GetString("SiteGroupAdminPage_SiteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Group Administration.
        /// </summary>
        internal static string SiteGroupAdminPage_uiTitle {
            get {
                return ResourceManager.GetString("SiteGroupAdminPage_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        internal static string UserAccount_btnUnlock {
            get {
                return ResourceManager.GetString("UserAccount_btnUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Approved.
        /// </summary>
        internal static string UserAccount_chkAccountApproved {
            get {
                return ResourceManager.GetString("UserAccount_chkAccountApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Q&amp;amp;A Info.
        /// </summary>
        internal static string UserAccount_chkChangePasswordQuestionAnswer {
            get {
                return ResourceManager.GetString("UserAccount_chkChangePasswordQuestionAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string UserAccount_chkResetPassword {
            get {
                return ResourceManager.GetString("UserAccount_chkResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created {0}, last updated {1}..
        /// </summary>
        internal static string UserAccount_CreatedInfo {
            get {
                return ResourceManager.GetString("UserAccount_CreatedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set yet.
        /// </summary>
        internal static string UserAccount_DefaultPasswordAnswer {
            get {
                return ResourceManager.GetString("UserAccount_DefaultPasswordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set yet.
        /// </summary>
        internal static string UserAccount_DefaultPasswordQuestion {
            get {
                return ResourceManager.GetString("UserAccount_DefaultPasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input password to change password question and answer..
        /// </summary>
        internal static string UserAccount_InputPasswordEmpty {
            get {
                return ResourceManager.GetString("UserAccount_InputPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change password question and answer because the password is incorrect.
        /// </summary>
        internal static string UserAccount_InputPasswordIncorrect {
            get {
                return ResourceManager.GetString("UserAccount_InputPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string UserAccount_lblEmail {
            get {
                return ResourceManager.GetString("UserAccount_lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string UserAccount_lblInputPassword {
            get {
                return ResourceManager.GetString("UserAccount_lblInputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string UserAccount_lblPassword {
            get {
                return ResourceManager.GetString("UserAccount_lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UserAccount_lblUsername {
            get {
                return ResourceManager.GetString("UserAccount_lblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account was locked out on {0}. Please uncheck box, and press Save to unlock account..
        /// </summary>
        internal static string UserAccount_LockedOutMessage {
            get {
                return ResourceManager.GetString("UserAccount_LockedOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password for user is &apos;{0}&apos;, please advise user.
        /// </summary>
        internal static string UserAccount_NewGenPassword {
            get {
                return ResourceManager.GetString("UserAccount_NewGenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Record.
        /// </summary>
        internal static string UserAccount_NewRecord {
            get {
                return ResourceManager.GetString("UserAccount_NewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is currently offline.
        /// </summary>
        internal static string UserAccount_OfflineTooltip {
            get {
                return ResourceManager.GetString("UserAccount_OfflineTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is currently online..
        /// </summary>
        internal static string UserAccount_OnlineTooltip {
            get {
                return ResourceManager.GetString("UserAccount_OnlineTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input password question and answer..
        /// </summary>
        internal static string UserAccount_QuestionPasswordEmpty {
            get {
                return ResourceManager.GetString("UserAccount_QuestionPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password answer.
        /// </summary>
        internal static string UserAccount_txtPasswordAnswerLabel {
            get {
                return ResourceManager.GetString("UserAccount_txtPasswordAnswerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password question.
        /// </summary>
        internal static string UserAccount_txtPasswordQuestionLabel {
            get {
                return ResourceManager.GetString("UserAccount_txtPasswordQuestionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and Password should not be empty..
        /// </summary>
        internal static string UserAccount_UserPasswordEmpty {
            get {
                return ResourceManager.GetString("UserAccount_UserPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been unlocked..
        /// </summary>
        internal static string UserAccount_UserUnlocked {
            get {
                return ResourceManager.GetString("UserAccount_UserUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account.
        /// </summary>
        internal static string UserAccountPage_uiTitle {
            get {
                return ResourceManager.GetString("UserAccountPage_uiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string UserRoleAuthAdminPage_lblRole {
            get {
                return ResourceManager.GetString("UserRoleAuthAdminPage_lblRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Group.
        /// </summary>
        internal static string UserRoleAuthAdminPage_lblSiteGroup {
            get {
                return ResourceManager.GetString("UserRoleAuthAdminPage_lblSiteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UserRoleAuthAdminPage_lblUser {
            get {
                return ResourceManager.GetString("UserRoleAuthAdminPage_lblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        internal static string UserRoleAuthAdminPage_uiTabComponents {
            get {
                return ResourceManager.GetString("UserRoleAuthAdminPage_uiTabComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string UserRoleAuthAdminPage_uiTabRoles {
            get {
                return ResourceManager.GetString("UserRoleAuthAdminPage_uiTabRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role Auth Admin.
        /// </summary>
        internal static string UserRoleAuthAdminPage_uiTitle {
            get {
                return ResourceManager.GetString("UserRoleAuthAdminPage_uiTitle", resourceCulture);
            }
        }
    }
}
